version: '3.7'

services:
  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sql.data;Database=CapacitacionMicroservicios.IdentityDb;User Id=postgres;Password=pass;
      - LocationApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5109
      - MarketingApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5110
      - BasketApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5103
      - OrderingApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5102
      - MobileShoppingAggClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5120
      - WebShoppingAggClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5121
    ports:
      - "5105:80"   

  catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sql.data;Database=CapacitacionMicroservicios.CatalogDb;User Id=postgres;Password=pass;
      - PicBaseUrl=http://localhost:5101/api/v1/catalog/items/[0]/pic/
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest        
      - UseCustomizationData=True
    ports:
      - "5101:80"
